/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface QueueReplicant {
	/**
	 * This is the title
	 */
	title: string;
	/**
	 * Author of the event
	 */
	author: string;
	/**
	 * 0:00 ~ 23:59
	 */
	time: string;
	category: string;
}
